### ISSUE TITLE
Why my GitHub status doesn't work?

### ISSUE THREAD

**Issue by fihesa192** [fihesa192/fihesa192#1]
<div align="center">

  <img src="https://github-readme-stats.vercel.app/api?username=fihesa192&show_icons=true&bg_color=0e2239&text_color=58a6ff&hide_border=true" width="54.25%">
  <img src="https://github-readme-stats.vercel.app/api/top-langs?username=fihesa192&layout=compact&bg_color=0e2239&text_color=58a6ff&hide_border=true" width="45.25%"> 
</div>

**Comment by webmaster1022** [comment]
Hi, Welcome to GitHub.
I have got same issue a few days ago too.
You can reference this repository to fix it.
```
https://github.com/lucky7123/github-stats-fix
```

**Comment by fihesa192** [comment]
Thank you, Senior.
It really works!
